### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 

### ISSUE THREAD

**Issue by Boxroma** [praekeltfoundation/junebug#172]
Hey there i am having issues installing junebug on my server.. Its Ubuntu 16.04 and my python version is 2.7.. the command i am typing is 
```sudo pip install jubebug```
I keep on getting this message 
``` Requirement already satisfied: pytz in /var/www/html/rapidpro/env/lib/python2.7/site-packages (from vumi>=0.6.18->junebug==0.1.40) (2017.2)
Collecting riak>=2.1 (from vumi>=0.6.18->junebug==0.1.40)
  Using cached https://files.pythonhosted.org/packages/85/f5/1a571ddc68f1dc7148f083f25210b7c7de8a9bc69d0ea5683ca6f3c189a9/riak-2.7.0.tar.gz
Collecting txJSON-RPC==0.5 (from vumi>=0.6.18->junebug==0.1.40)
  Using cached https://files.pythonhosted.org/packages/83/68/fb79f7a5154cb9fea93ae1a00b2d0aed3527c79b8a30649a902a3eaf7846/txJSON-RPC-0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Warning: '%s' not a legal ReST filename.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ua9TBG/txJSON-RPC/setup.py", line 27, in <module>
        out=True),
      File "/tmp/pip-install-ua9TBG/txJSON-RPC/txjsonrpc/util/dist.py", line 121, in catReST
        report = validateReST(res)
      File "/tmp/pip-install-ua9TBG/txJSON-RPC/txjsonrpc/util/dist.py", line 86, in validateReST
        return _validateReST(text)
      File "/tmp/pip-install-ua9TBG/txJSON-RPC/txjsonrpc/util/dist.py", line 76, in _validateReST
        parser.parse(text, doc)
      File "/var/www/html/rapidpro/env/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 185, in parse
        self.statemachine.run(inputlines, document, inliner=self.inliner)
      File "/var/www/html/rapidpro/env/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 157, in run
        inliner.init_customizations(document.settings)
      File "/var/www/html/rapidpro/env/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 470, in init_customizations
        if settings.character_level_inline_markup:
    AttributeError: Values instance has no attribute 'character_level_inline_markup'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ua9TBG/txJSON-RPC/
```

I only copied the last part but if more is needed let me know..

**Comment by rudigiesler** [comment]
Hi @Boxroma 

This seems like a bug in the `docutils` package: https://github.com/oubiwann/txjsonrpc/issues/24 .

I would suggest updating your `docutils` version through `pip install --upgrade docutils`

**Comment by sewagodimo** [comment]
Hey Boroma,
it looks related to this issue [there is a fix on here]:
https://github.com/oubiwann/txjsonrpc/issues/24

**Comment by Boxroma** [comment]
Thanks so much updating helped!..

**Comment by Boxroma** [comment]
Hey @rudigiesler i am trying to run the installation in Docker now and updating the docutils dosnt seem to work.

**Comment by rudigiesler** [comment]
@Boxroma You shouldn't need to install Junebug in your docker image, we already have a Junebug docker image that you can just use: https://hub.docker.com/r/praekeltfoundation/junebug/
